version: '3'

# networks
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  # internal network
  internal:
    driver: bridge

# volumes
volumes:
  # MySQL data volume
  devitools-mysql_data:
    driver: local
  # Redis data volume
  devitools-redis_data:
    driver: local

# services
services:

  # Symfony service to provide api
  devitools-nginx:
    image: webdevops/php-nginx:7.4
    container_name: devitools-nginx
    restart: always
    networks:
      - internal
      - reverse-proxy
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - .docker/devitools-nginx/opt/docker/etc/nginx/vhost.common.d/cache.conf:/opt/docker/etc/nginx/vhost.common.d/cache.conf
    depends_on:
      - devitools-mysql
      - devitools-redis
    links:
      - devitools-mysql
      - devitools-redis
    environment:
      - VIRTUAL_HOST=${DOCKER_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${DOCKER_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${DOCKER_LETSENCRYPT_EMAIL}
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - XDEBUG_PROFILER_ENABLE=Off
      - PHP_DISPLAY_ERRORS=0
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_POST_MAX_SIZE=50M
      - PHP_UPLOAD_MAX_FILESIZE=50M

  # database
  devitools-mysql:
    image: mysql:5.7
    container_name: devitools-mysql
    restart: always
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - devitools-mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  # cache
  devitools-redis:
    image: redis:4.0
    container_name: devitools-redis
    restart: always
    networks:
      - internal
    command: --appendonly yes
    volumes:
      - devitools-redis_data:/data

  # devitools-queue
  devitools-queue:
    image: webdevops/php-nginx:7.4
    container_name: devitools-queue
    restart: always
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - .docker/devitools-queue/opt/docker/etc/supervisor.d/php-fpm.conf:/opt/docker/etc/supervisor.d/php-fpm.conf
    depends_on:
      - devitools-mysql
      - devitools-redis
