version: '3'

# services
services:

  # app
  quasar-app:
    container_name: ${DOCKER_SERVICE_APP}
    user: node
    image: tevun/quasar:latest
    working_dir: /var/www/app
    command: bash /var/www/app/docker-compose.sh
    volumes:
      - .:/var/www/app
      - ./.bin:/home/node/bin
    ports:
      - 8000:8000
