version: '3'

# Networks
networks:
  # Internal network
  internal:
    driver: bridge

# Volumes
volumes:
  # MySQL volume
  devitools-mysql_data:
    driver: local
  # Redis volume
  devitools-redis_data:
    driver: local

# Services
services:

  # Nginx
  devitools-nginx:
    image: webdevops/php-nginx-dev:7.4
    container_name: devitools-nginx
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - .docker/devitools-nginx/opt/docker/etc/nginx/vhost.common.d/cache.conf:/opt/docker/etc/nginx/vhost.common.d/cache.conf
#      - .docker/devitools-nginx/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - devitools-mysql
      - devitools-redis
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - PHP_DISPLAY_ERRORS=0
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=500M
      - PHP_DEBUGGER="xdebug"
      #      - PHP_IDE_CONFIG="serverName=_"
      - XDEBUG_REMOTE_AUTOSTART=On
      - XDEBUG_REMOTE_CONNECT_BACK=Off
      - XDEBUG_REMOTE_HOST=host.docker.internal
      - XDEBUG_REMOTE_PORT=9090
      - XDEBUG_PROFILER_ENABLE=Off
      - PHP_DATE_TIMEZONE=UTC
    expose:
      - 9090
    ports:
      - 8080:80

  # MySQL
  devitools-mysql:
    image: mysql:5.7
    container_name: devitools-mysql
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - devitools-mysql_data:/var/lib/mysql
      - .:/var/www/app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  # Redis
  devitools-redis:
    image: redis:4.0
    container_name: devitools-redis
    command: --appendonly yes
    networks:
      - internal
    volumes:
      - devitools-redis_data:/data
    ports:
      - 6379:6379

  # Queue SupervisorD
  devitools-queue:
    image: webdevops/php-nginx:7.4
    container_name: devitools-queue
    working_dir: /var/www/app
    networks:
      - internal
    volumes:
      - .:/var/www/app
      - .docker/devitools-queue/opt/docker/etc/supervisor.d/php-fpm.conf:/opt/docker/etc/supervisor.d/php-fpm.conf
    depends_on:
      - devitools-mysql
      - devitools-redis
